"""Typed environment configuration for the observability gateway."""

from __future__ import annotations

import math
import os
from dataclasses import dataclass
from ipaddress import ip_address
from pathlib import Path

from dotenv import load_dotenv

from .shared.errors import ConfigurationError


PROJECT_ROOT = Path(__file__).resolve().parents[2]
ENV_FILE = PROJECT_ROOT / ".env"

_TRUE_VALUES = {"true"}
_FALSE_VALUES = {"false"}
_LOG_LEVELS = {
    "DEBUG",
    "INFO",
    "WARNING",
    "ERROR",
    "CRITICAL",
}

_AGENT_IDENTITY_VARIABLES = (
    "AGENT_ID",
    "AGENT365OBSERVABILITY__TENANTID",
)
_OBSERVABILITY_METADATA_VARIABLES = (
    "AGENT365OBSERVABILITY__AGENTID",
    "AGENT365OBSERVABILITY__AGENTNAME",
    "AGENT365OBSERVABILITY__AGENTDESCRIPTION",
    "AGENT365OBSERVABILITY__AGENTBLUEPRINTID",
)
_AGENTIC_CONNECTION_VARIABLES = (
    "CONNECTIONS__SERVICE_CONNECTION__SETTINGS__CLIENTID",
    "CONNECTIONS__SERVICE_CONNECTION__SETTINGS__CLIENTSECRET",
    "CONNECTIONS__SERVICE_CONNECTION__SETTINGS__TENANTID",
    "CONNECTIONS__SERVICE_CONNECTION__SETTINGS__SCOPES",
    "AGENTAPPLICATION__USERAUTHORIZATION__HANDLERS__AGENTIC__SETTINGS__TYPE",
    "AGENTAPPLICATION__USERAUTHORIZATION__HANDLERS__AGENTIC__SETTINGS__ALT_BLUEPRINT_NAME",
    "AGENTAPPLICATION__USERAUTHORIZATION__HANDLERS__AGENTIC__SETTINGS__SCOPES",
    "CONNECTIONSMAP__0__SERVICEURL",
    "CONNECTIONSMAP__0__CONNECTION",
)


@dataclass(frozen=True)
class ServerConfig:
    """HTTP listener and request-limit settings."""

    host: str
    port: int
    api_key: str | None
    max_request_bytes: int


@dataclass(frozen=True)
class PurviewConfig:
    """Microsoft Graph Purview DLP settings."""

    application_id: str
    app_name: str
    app_version: str
    graph_base_url: str
    request_timeout_seconds: float
    scope_cache_seconds: float
    enabled: bool
    fail_closed: bool


@dataclass(frozen=True)
class AgentConfig:
    """Agent instance and blueprint identities generated by Agent 365."""

    agent_id: str
    blueprint_id: str
    tenant_id: str


@dataclass(frozen=True)
class AgentDetailsConfig:
    """Agent metadata attached to Agent 365 observability spans."""

    agent_id: str
    agent_name: str
    agent_description: str
    agent_blueprint_id: str
    tenant_id: str


@dataclass(frozen=True)
class ObservabilityConfig:
    """Agent 365 OpenTelemetry behavior and span metadata."""

    agent: AgentDetailsConfig
    enabled: bool
    remote_export_enabled: bool
    use_s2s_endpoint: bool
    log_level: str
    console_enabled: bool


@dataclass(frozen=True)
class GatewayConfig:
    """Complete validated gateway configuration."""

    server: ServerConfig
    purview: PurviewConfig
    agent: AgentConfig
    observability: ObservabilityConfig


def load_config(env_file: Path | None = None) -> GatewayConfig:
    """Load an agent-local ``.env`` without overriding process variables."""

    path = env_file or ENV_FILE
    if not path.is_file():
        raise ConfigurationError(f"Environment file not found: {path}")
    load_dotenv(dotenv_path=path, override=False)

    purview_enabled = _boolean("PURVIEW_DLP_ENABLED", True)
    observability_enabled = _boolean("ENABLE_A365_OBSERVABILITY", True)
    remote_export_enabled = _boolean(
        "ENABLE_A365_OBSERVABILITY_EXPORTER",
        True,
    )
    if remote_export_enabled and not observability_enabled:
        raise ConfigurationError(
            "ENABLE_A365_OBSERVABILITY_EXPORTER cannot be true when "
            "ENABLE_A365_OBSERVABILITY is false"
        )

    required_names = list(_AGENT_IDENTITY_VARIABLES)
    required_names.extend(_OBSERVABILITY_METADATA_VARIABLES)
    required_names.extend(_AGENTIC_CONNECTION_VARIABLES)
    values = _required_values(required_names)

    blueprint_id = values["AGENT_ID"]
    agent_id = values["AGENT365OBSERVABILITY__AGENTID"]
    tenant_id = values["AGENT365OBSERVABILITY__TENANTID"]
    purview_application_id = (
        _optional_string("PURVIEW_APPLICATION_ID") or agent_id
    )

    log_level = _string("A365_OBSERVABILITY_LOG_LEVEL", "INFO").upper()
    if log_level not in _LOG_LEVELS:
        supported = ", ".join(sorted(_LOG_LEVELS))
        raise ConfigurationError(
            "A365_OBSERVABILITY_LOG_LEVEL must be one of: " f"{supported}"
        )

    server = ServerConfig(
        host=_string("OBS_GATEWAY_HOST", "127.0.0.1"),
        port=_integer("OBS_GATEWAY_PORT", 4318, minimum=1, maximum=65_535),
        api_key=_optional_string("OBS_GATEWAY_API_KEY"),
        max_request_bytes=_integer(
            "OBS_GATEWAY_MAX_REQUEST_BYTES",
            1_048_576,
            minimum=1,
        ),
    )
    if not _is_loopback_host(server.host) and not server.api_key:
        raise ConfigurationError(
            "OBS_GATEWAY_API_KEY is required when OBS_GATEWAY_HOST is not "
            "a loopback address"
        )
    purview = PurviewConfig(
        application_id=purview_application_id,
        app_name=_string(
            "PURVIEW_APP_NAME",
            "Agent 365 Observability Gateway",
        ),
        app_version=_string("PURVIEW_APP_VERSION", "1.0"),
        graph_base_url=_string(
            "PURVIEW_GRAPH_BASE_URL",
            "https://graph.microsoft.com/v1.0",
        ).rstrip("/"),
        request_timeout_seconds=_number(
            "PURVIEW_TIMEOUT_SECONDS",
            15.0,
            minimum=0.001,
        ),
        scope_cache_seconds=_number(
            "PURVIEW_SCOPE_CACHE_SECONDS",
            3600.0,
            minimum=0.0,
        ),
        enabled=purview_enabled,
        fail_closed=_boolean("PURVIEW_DLP_FAIL_CLOSED", True),
    )
    agent = AgentConfig(
        agent_id=agent_id,
        blueprint_id=blueprint_id,
        tenant_id=tenant_id,
    )
    observability_agent = AgentDetailsConfig(
        agent_id=agent_id,
        agent_name=values.get(
            "AGENT365OBSERVABILITY__AGENTNAME",
            "Agent 365 Gateway",
        ),
        agent_description=values.get(
            "AGENT365OBSERVABILITY__AGENTDESCRIPTION",
            "Agent 365 observability gateway",
        ),
        agent_blueprint_id=values.get(
            "AGENT365OBSERVABILITY__AGENTBLUEPRINTID",
            blueprint_id,
        ),
        tenant_id=tenant_id,
    )
    observability = ObservabilityConfig(
        agent=observability_agent,
        enabled=observability_enabled,
        remote_export_enabled=remote_export_enabled,
        use_s2s_endpoint=_boolean("A365_USE_S2S_ENDPOINT", True),
        log_level=log_level,
        console_enabled=_boolean("A365_OBSERVABILITY_CONSOLE", False),
    )
    return GatewayConfig(
        server=server,
        purview=purview,
        agent=agent,
        observability=observability,
    )


def _required_values(names: list[str]) -> dict[str, str]:
    unique_names = tuple(dict.fromkeys(names))
    values = {
        name: value
        for name in unique_names
        if (value := os.getenv(name, "").strip())
    }
    missing = [name for name in unique_names if name not in values]
    if missing:
        raise ConfigurationError(
            "Missing required environment variables: " + ", ".join(missing)
        )
    return values


def _string(name: str, default: str) -> str:
    value = os.getenv(name)
    if value is None or not value.strip():
        return default
    return value.strip()


def _optional_string(name: str) -> str | None:
    value = os.getenv(name, "").strip()
    return value or None


def _boolean(name: str, default: bool) -> bool:
    raw_value = os.getenv(name)
    if raw_value is None or not raw_value.strip():
        return default
    value = raw_value.strip().lower()
    if value in _TRUE_VALUES:
        return True
    if value in _FALSE_VALUES:
        return False
    raise ConfigurationError(f"{name} must be true or false")


def _integer(
    name: str,
    default: int,
    *,
    minimum: int | None = None,
    maximum: int | None = None,
) -> int:
    raw_value = os.getenv(name)
    if raw_value is None or not raw_value.strip():
        value = default
    else:
        try:
            value = int(raw_value)
        except ValueError as exc:
            raise ConfigurationError(f"{name} must be an integer") from exc
    _validate_range(name, value, minimum=minimum, maximum=maximum)
    return value


def _number(
    name: str,
    default: float,
    *,
    minimum: float | None = None,
    maximum: float | None = None,
) -> float:
    raw_value = os.getenv(name)
    if raw_value is None or not raw_value.strip():
        value = default
    else:
        try:
            value = float(raw_value)
        except ValueError as exc:
            raise ConfigurationError(f"{name} must be a number") from exc
    if not math.isfinite(value):
        raise ConfigurationError(f"{name} must be a finite number")
    _validate_range(name, value, minimum=minimum, maximum=maximum)
    return value


def _validate_range(
    name: str,
    value: int | float,
    *,
    minimum: int | float | None,
    maximum: int | float | None,
) -> None:
    if minimum is not None and value < minimum:
        raise ConfigurationError(f"{name} must be at least {minimum:g}")
    if maximum is not None and value > maximum:
        raise ConfigurationError(f"{name} must be at most {maximum:g}")


def _is_loopback_host(host: str) -> bool:
    if host.lower() == "localhost":
        return True
    try:
        return ip_address(host).is_loopback
    except ValueError:
        return False